name: Page Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check date and run monitor script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          TODAY=$(date -u +%Y-%m-%d)
          STOP_DATE="2025-07-28"
          if [[ "$TODAY" > "$STOP_DATE" ]]; then
            echo "Date is after $STOP_DATE. Exiting workflow."
            exit 0
          fi
          python python_monitor_script.py
      - name: Commit snapshot if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add page_snapshot.json
          git diff --cached --quiet || git commit -m "Update snapshot"
          git push